# Generated by Django 6.0 on 2025-12-22 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS store_cart CASCADE;",
            reverse_sql="""
                        CREATE TABLE store_cart
                        (
                            id         BIGSERIAL PRIMARY KEY,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                        );
                        """
        ),

        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS store_cartitem CASCADE;",
            reverse_sql="""
                        CREATE TABLE store_cartitem
                        (
                            id         BIGSERIAL PRIMARY KEY,
                            cart_id    BIGINT  NOT NULL,
                            product_id BIGINT  NOT NULL,
                            quantity   INTEGER NOT NULL CHECK (quantity >= 1),
                            FOREIGN KEY (cart_id) REFERENCES store_cart (id) ON DELETE CASCADE,
                            FOREIGN KEY (product_id) REFERENCES store_product (id) ON DELETE CASCADE
                        );
                        """
        ),

        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product'),
        ),
    ]
